baseURL = 'https://qinhuilin.github.io/oldss/'
languageCode = 'en-us'
publishDir = 'docs'
title = '老有所养'
theme = 'ananke'


hasCJKLanguage = true
summaryLength = 29

canonifyurls = true
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/posts/"
weight = 60

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

